#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.nginx.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - name: https
    port: {{ $.Values.config.nginx.int.https_port }}
    targetPort: {{ $.Values.config.nginx.int.https_port }}
    nodePort: {{ $.Values.config.nginx.ext.https_port }}
  - name: mqtt
    port: {{ $.Values.config.nginx.int.mqtt_port }}
    targetPort: {{ $.Values.config.nginx.int.mqtt_port }}
    nodePort: {{ $.Values.config.nginx.ext.mqtt_port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: deployment-nginx
  namespace: {{ .Values.namespace }}

spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-proxy
        image: bitnami/nginx:1.29-debian-12
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: no_proxy
          value: "ia-grafana,ia-time-series-analytics-microservice,ia-mqtt-broker,${no_proxy}"
        - name: NO_PROXY
          value: "ia-grafana,ia-time-series-analytics-microservice,ia-mqtt-broker,${no_proxy}"
        volumeMounts:
        - name: nginx-conf
          mountPath: /opt/bitnami/nginx/conf/nginx.conf
          subPath: nginx.conf
        - name: nginx-cert-gen
          mountPath: /docker-entrypoint-initdb.d/nginx-cert-gen.sh
          subPath: nginx-cert-gen.sh
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: nginx-cert-gen
        configMap:
          name: nginx-cert-gen
