---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-broker-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-broker-tls
  issuerRef:
    name: {{ .Release.Name }}-ca-issuer
    kind: Issuer
  commonName: "broker.scenescape.intel.com"
  dnsNames:
  - "broker.scenescape.intel.com"
  - "{{ .Release.Name }}-broker"
  - "{{ .Release.Name }}-broker.{{ .Release.Namespace }}"
  - "{{ .Release.Name }}-broker.{{ .Release.Namespace }}.svc.cluster.local"
  duration: 8760h
  renewBefore: 720h
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-web-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-web-tls
  issuerRef:
    name: {{ .Release.Name }}-ca-issuer
    kind: Issuer
  commonName: "web.scenescape.intel.com"
  dnsNames:
  - "web.scenescape.intel.com"
  - "{{ .Release.Name }}-web"
  - "{{ .Release.Name }}-web.{{ .Release.Namespace }}"
  - "{{ .Release.Name }}-web.{{ .Release.Namespace }}.svc.cluster.local"
  duration: 8760h
  renewBefore: 720h
