apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "image_based_video_search.fullname" . }}-nginx
  labels:
    {{- include "image_based_video_search.labels" . | nindent 4 }}
    katenary.v3/component: nginx
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: {{ include "image_based_video_search.fullname" . }}-nginx
  template:
    metadata:
      labels:
        app: {{ include "image_based_video_search.fullname" . }}-nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/nginx/ssl
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      volumes:
        - name: ssl-certs
          emptyDir: {}
